### ISSUE TITLE
想询问下，详细学习清单

### ISSUE THREAD

**Issue by lllong33** [sunnyandgood/BigData#1]
sunnyandgood，你好，
多谢的你笔记目录，让我对技术栈有更清晰的认识。
我基础比较弱，你的笔记看着有点吃力，有时候被一个点卡很久。
想询问下你是看哪些相关书籍学习的，笔记的主要来源？

**Comment by feihong247** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
